---
on:
  - push
  - pull_request

name: build code
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: print node version
        run: |
          node -v
          npm -v

      - name: clean install dependencies
        run: npm ci

      - name: build typescript
        run: npm run build
