---
on:
  - push
  - pull_request

jobs:
  setup:
    name: setup
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: print node version
        run: |
          node -v
          npm -v

      - name: clean install dependencies
        run: npm ci

  lint:
    name: lint
    runs-on: ubuntu-20.04
    needs: setup

    steps:
      - name: lint typescript
        run: npm run lint


  build:
    name: build
    runs-on: ubuntu-20.04
    needs: setup

    steps:
      - name: build typescript
        run: npm run build
